{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "c931d48b-4310-4a20-a524-63dd78c4f6db",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Epoch 1/10 Loss: 68.9830\n",
      "Epoch 2/10 Loss: 31.4060\n",
      "Epoch 3/10 Loss: 0.2720\n",
      "Epoch 4/10 Loss: 6.9334\n",
      "Epoch 5/10 Loss: 4.8677\n",
      "Epoch 6/10 Loss: 3.2523\n",
      "Epoch 7/10 Loss: 2.3101\n",
      "Epoch 8/10 Loss: 0.4044\n",
      "Epoch 9/10 Loss: 1.3129\n",
      "Epoch 10/10 Loss: 3.9129\n",
      "\n",
      "LSTM + prediktor alapú két-havi koefficiensek:\n",
      "bimonth\n",
      "Jan-Feb    0.701422\n",
      "Jul-Aug    0.883378\n",
      "Mar-Apr    0.991649\n",
      "May-Jun    0.574083\n",
      "Nov-Dec   -0.374349\n",
      "Sep-Oct    0.823573\n",
      "Name: k_lstm, dtype: float64\n",
      "\n",
      "Kimenet elkészült: vizhozam_2018_2019_LSTM_2havi_koeff.xlsx\n"
     ]
    }
   ],
   "source": [
    "import torch\n",
    "import torch.nn as nn\n",
    "from torch.utils.data import Dataset, DataLoader\n",
    "import pandas as pd\n",
    "import numpy as np\n",
    "\n",
    "# =========================================================\n",
    "# PARAMÉTEREK\n",
    "# =========================================================\n",
    "SEQ_LEN = 30\n",
    "BATCH_SIZE = 64\n",
    "EPOCHS = 10\n",
    "LR = 5e-4\n",
    "RANDOM_SEED = 42\n",
    "\n",
    "DATE_COL = \"Idopont\"\n",
    "RAW_COL = \"Nyers\"\n",
    "TARGET_COL = \"Korrigalt\"\n",
    "\n",
    "TRAIN_START = \"2020-01-01\"\n",
    "TRAIN_END   = \"2024-12-31\"\n",
    "\n",
    "PRED_FILE = \"prediktorok.xlsx\"\n",
    "PRED_DATE_COL = \"datum\"\n",
    "\n",
    "SHEET_CSAP   = \"pred_csap\"\n",
    "SHEET_HOM    = \"pred_hom\"\n",
    "SHEET_SZELSB = \"pred_szelseb\"\n",
    "SHEET_SZELIR = \"pred_szelir\"\n",
    "\n",
    "CSAP_COL   = \"csapadek\"\n",
    "HOM_COL    = \"homerseklet\"\n",
    "SZELSB_COL = \"szelsebesseg\"\n",
    "SZELIR_COL = \"szelirany\"\n",
    "\n",
    "torch.manual_seed(RANDOM_SEED)\n",
    "np.random.seed(RANDOM_SEED)\n",
    "\n",
    "# =========================================================\n",
    "# SEGÉDFÜGGVÉNYEK\n",
    "# =========================================================\n",
    "def read_daily_series(sheet, value_col):\n",
    "    \"\"\"\n",
    "    Napi prediktor beolvasása a PRED_FILE adott munkalapjáról.\n",
    "    Visszaad: pandas Series, DateTimeIndex-szel (napi), duplikált napok átlagolva.\n",
    "    \"\"\"\n",
    "    dfp = pd.read_excel(PRED_FILE, sheet_name=sheet)\n",
    "    dfp[PRED_DATE_COL] = pd.to_datetime(dfp[PRED_DATE_COL], errors=\"coerce\")\n",
    "\n",
    "    dfp = dfp.dropna(subset=[PRED_DATE_COL]).copy()\n",
    "    dfp = dfp.sort_values(PRED_DATE_COL)\n",
    "    dfp = dfp[[PRED_DATE_COL, value_col]].copy()\n",
    "\n",
    "    # Duplikált dátumok kezelése: átlag\n",
    "    s = dfp.groupby(PRED_DATE_COL)[value_col].mean()\n",
    "    s.index = pd.to_datetime(s.index)\n",
    "    s = s.sort_index()\n",
    "    return s\n",
    "\n",
    "def bimonth(m):\n",
    "    if m in [1, 2]:\n",
    "        return \"Jan-Feb\"\n",
    "    elif m in [3, 4]:\n",
    "        return \"Mar-Apr\"\n",
    "    elif m in [5, 6]:\n",
    "        return \"May-Jun\"\n",
    "    elif m in [7, 8]:\n",
    "        return \"Jul-Aug\"\n",
    "    elif m in [9, 10]:\n",
    "        return \"Sep-Oct\"\n",
    "    else:\n",
    "        return \"Nov-Dec\"\n",
    "\n",
    "def fit_standardizer(df, cols):\n",
    "    mu = df[cols].mean()\n",
    "    sd = df[cols].std().replace(0, 1.0)\n",
    "    return mu, sd\n",
    "\n",
    "def apply_standardizer(df, cols, mu, sd):\n",
    "    out = df.copy()\n",
    "    out[cols] = (out[cols] - mu) / sd\n",
    "    return out\n",
    "\n",
    "# =========================================================\n",
    "# DATASET\n",
    "# =========================================================\n",
    "class CorrectionDataset(Dataset):\n",
    "    def __init__(self, df, feature_cols, target_col):\n",
    "        self.X = df[feature_cols].values.astype(np.float32)\n",
    "        self.y = df[target_col].values.astype(np.float32)\n",
    "\n",
    "    def __len__(self):\n",
    "        return len(self.y) - SEQ_LEN\n",
    "\n",
    "    def __getitem__(self, idx):\n",
    "        return (\n",
    "            torch.tensor(self.X[idx:idx+SEQ_LEN]),\n",
    "            torch.tensor(self.y[idx+SEQ_LEN])\n",
    "        )\n",
    "\n",
    "# =========================================================\n",
    "# LSTM MODELL\n",
    "# =========================================================\n",
    "class LSTMCorrection(nn.Module):\n",
    "    def __init__(self, input_size, hidden_size=64, num_layers=2):\n",
    "        super().__init__()\n",
    "        self.lstm = nn.LSTM(input_size, hidden_size, num_layers, batch_first=True)\n",
    "        self.fc = nn.Linear(hidden_size, 1)\n",
    "\n",
    "    def forward(self, x):\n",
    "        out, _ = self.lstm(x)\n",
    "        return self.fc(out[:, -1, :])\n",
    "\n",
    "# =========================================================\n",
    "# 1) PREDIKTOROK (NAPI → dátum szerinti illesztés)\n",
    "# =========================================================\n",
    "csap_s   = read_daily_series(SHEET_CSAP, CSAP_COL)\n",
    "hom_s    = read_daily_series(SHEET_HOM, HOM_COL)\n",
    "szelsb_s = read_daily_series(SHEET_SZELSB, SZELSB_COL)\n",
    "szelir_s = read_daily_series(SHEET_SZELIR, SZELIR_COL)\n",
    "\n",
    "# =========================================================\n",
    "# 2) TANÍTÓ ADATOK (2020–2024)\n",
    "# =========================================================\n",
    "df_train = pd.read_excel(\"uj_vizhozam_tanito.xlsx\")\n",
    "df_train[DATE_COL] = pd.to_datetime(df_train[DATE_COL])\n",
    "df_train = df_train.set_index(DATE_COL).sort_index()\n",
    "df_train = df_train.loc[TRAIN_START:TRAIN_END]\n",
    "\n",
    "idx = pd.date_range(df_train.index.min(), df_train.index.max(), freq=\"D\")\n",
    "df_train = df_train.reindex(idx)\n",
    "\n",
    "df_train[RAW_COL] = df_train[RAW_COL].interpolate(\"time\").ffill().bfill()\n",
    "df_train[TARGET_COL] = df_train[TARGET_COL].interpolate(\"time\").ffill().bfill()\n",
    "\n",
    "# Prediktorok dátum szerinti hozzárendelése (join)\n",
    "df_train[CSAP_COL]   = csap_s.reindex(df_train.index)\n",
    "df_train[HOM_COL]    = hom_s.reindex(df_train.index)\n",
    "df_train[SZELSB_COL] = szelsb_s.reindex(df_train.index)\n",
    "df_train[SZELIR_COL] = szelir_s.reindex(df_train.index)\n",
    "\n",
    "# Hiányok kezelése a prediktorokban\n",
    "# (napi prediktoroknál ez a legkevesebb \"érdemi változtatás\": időbeli interpoláció + szélek kitöltése)\n",
    "pred_cols = [CSAP_COL, HOM_COL, SZELSB_COL, SZELIR_COL]\n",
    "df_train[pred_cols] = df_train[pred_cols].interpolate(\"time\").ffill().bfill()\n",
    "\n",
    "feature_cols = [RAW_COL, CSAP_COL, HOM_COL, SZELSB_COL, SZELIR_COL]\n",
    "\n",
    "mu, sd = fit_standardizer(df_train, feature_cols)\n",
    "df_train_scaled = apply_standardizer(df_train, feature_cols, mu, sd)\n",
    "\n",
    "# =========================================================\n",
    "# 3) LSTM TANÍTÁS\n",
    "# =========================================================\n",
    "dataset = CorrectionDataset(df_train_scaled, feature_cols, TARGET_COL)\n",
    "loader = DataLoader(dataset, batch_size=BATCH_SIZE, shuffle=True)\n",
    "\n",
    "model = LSTMCorrection(len(feature_cols))\n",
    "optimizer = torch.optim.Adam(model.parameters(), lr=LR)\n",
    "criterion = nn.MSELoss()\n",
    "\n",
    "model.train()\n",
    "for e in range(EPOCHS):\n",
    "    for X, y in loader:\n",
    "        optimizer.zero_grad()\n",
    "        loss = criterion(model(X).squeeze(), y)\n",
    "        loss.backward()\n",
    "        optimizer.step()\n",
    "    print(f\"Epoch {e+1}/{EPOCHS} Loss: {loss.item():.4f}\")\n",
    "\n",
    "# =========================================================\n",
    "# 4) LSTM VISSZAJÓSLÁS A TANÍTÓ IDŐSZAKRA\n",
    "# =========================================================\n",
    "model.eval()\n",
    "preds_train = [np.nan]*SEQ_LEN\n",
    "with torch.no_grad():\n",
    "    Xall = df_train_scaled[feature_cols].values.astype(np.float32)\n",
    "    for i in range(len(df_train_scaled)-SEQ_LEN):\n",
    "        preds_train.append(model(torch.tensor(Xall[i:i+SEQ_LEN]).unsqueeze(0)).item())\n",
    "\n",
    "df_train[\"Korrigalt_LSTM\"] = preds_train\n",
    "\n",
    "# =========================================================\n",
    "# 5) KÉT-HAVI KOEFFICIENSEK (LSTM-ALAPÚ)\n",
    "# =========================================================\n",
    "df_train[\"bimonth\"] = df_train.index.month.map(bimonth)\n",
    "df_train[\"k_lstm\"] = df_train[\"Korrigalt_LSTM\"] / df_train[RAW_COL]\n",
    "df_train[\"k_lstm\"] = df_train[\"k_lstm\"].replace([np.inf, -np.inf], np.nan)\n",
    "\n",
    "bimonth_coeff = df_train.groupby(\"bimonth\")[\"k_lstm\"].mean()\n",
    "\n",
    "print(\"\\nLSTM + prediktor alapú két-havi koefficiensek:\")\n",
    "print(bimonth_coeff)\n",
    "\n",
    "# =========================================================\n",
    "# 6) ALKALMAZÁS 2018–2019-RE (PREDIKTOR NÉLKÜL)\n",
    "# =========================================================\n",
    "df_fix = pd.read_excel(\"uj_vizhozam_uj.xlsx\")\n",
    "df_fix[DATE_COL] = pd.to_datetime(df_fix[DATE_COL])\n",
    "df_fix = df_fix.set_index(DATE_COL).sort_index()\n",
    "df_fix = df_fix.loc[\"2018-01-01\":\"2019-12-31\"]\n",
    "\n",
    "idx_fix = pd.date_range(df_fix.index.min(), df_fix.index.max(), freq=\"D\")\n",
    "df_fix = df_fix.reindex(idx_fix)\n",
    "df_fix[RAW_COL] = df_fix[RAW_COL].interpolate(\"time\").ffill().bfill()\n",
    "\n",
    "df_fix[\"bimonth\"] = df_fix.index.month.map(bimonth)\n",
    "df_fix[\"Korrigalt_pred\"] = df_fix[RAW_COL] * df_fix[\"bimonth\"].map(bimonth_coeff)\n",
    "\n",
    "out = df_fix.reset_index().rename(columns={\"index\": DATE_COL})\n",
    "out.to_excel(\"vizhozam_2018_2019_LSTM_2havi_koeff.xlsx\", index=False)\n",
    "\n",
    "print(\"\\nKimenet elkészült: vizhozam_2018_2019_LSTM_2havi_koeff.xlsx\")\n"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": 3,
   "id": "9a0dc265-ad18-4c56-a65d-ed2785979f13",
   "metadata": {},
   "outputs": [
    {
     "name": "stdout",
     "output_type": "stream",
     "text": [
      "Base MSE: 2.204526325847948\n",
      "              mean_delta_mse  std_delta_mse\n",
      "Nyers              14.589744       0.541833\n",
      "csapadek            0.388964       0.094362\n",
      "homerseklet         0.177086       0.014639\n",
      "szelirany           0.104128       0.014674\n",
      "szelsebesseg        0.030148       0.008767\n"
     ]
    }
   ],
   "source": [
    "import numpy as np\n",
    "import pandas as pd\n",
    "import torch\n",
    "\n",
    "def eval_mse(model, df_scaled, feature_cols, target_col, seq_len=30):\n",
    "    model.eval()\n",
    "    X = df_scaled[feature_cols].values.astype(np.float32)\n",
    "    y = df_scaled[target_col].values.astype(np.float32)\n",
    "\n",
    "    preds = []\n",
    "    trues = []\n",
    "    with torch.no_grad():\n",
    "        for i in range(len(df_scaled) - seq_len):\n",
    "            X_seq = torch.tensor(X[i:i+seq_len]).unsqueeze(0)\n",
    "            preds.append(model(X_seq).item())\n",
    "            trues.append(y[i+seq_len])\n",
    "    preds = np.array(preds)\n",
    "    trues = np.array(trues)\n",
    "    return np.mean((preds - trues)**2)\n",
    "\n",
    "def permutation_importance(model, df_scaled, feature_cols, target_col, seq_len=30, n_repeats=5, seed=0):\n",
    "    rng = np.random.default_rng(seed)\n",
    "    base = eval_mse(model, df_scaled, feature_cols, target_col, seq_len)\n",
    "    out = {}\n",
    "    for col in feature_cols:\n",
    "        deltas = []\n",
    "        for _ in range(n_repeats):\n",
    "            df_perm = df_scaled.copy()\n",
    "            df_perm[col] = rng.permutation(df_perm[col].values)  # időbeli szétkeverés\n",
    "            mse_perm = eval_mse(model, df_perm, feature_cols, target_col, seq_len)\n",
    "            deltas.append(mse_perm - base)\n",
    "        out[col] = (np.mean(deltas), np.std(deltas))\n",
    "    res = pd.DataFrame(out, index=[\"mean_delta_mse\", \"std_delta_mse\"]).T\n",
    "    res = res.sort_values(\"mean_delta_mse\", ascending=False)\n",
    "    return base, res\n",
    "\n",
    "base_mse, pimps = permutation_importance(model, df_train_scaled, feature_cols, TARGET_COL, seq_len=SEQ_LEN)\n",
    "print(\"Base MSE:\", base_mse)\n",
    "print(pimps)"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "145b4ac7-223f-4870-875a-9e6e92212b82",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.12.7"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
